tasks:
  - name: Python Setup
    before: pip install --user pipenv
    init: |  
      unset PIP_USER
      unset PROMPT_COMMAND
      pipenv install
      pipenv install python-dotenv
    command: |
      pipenv shell

  - name: Restore .env file
    command: |
      if [ -f .env ]; then
        echo "Found .env in workspace"
      else
        echo "Creating .env file"
        echo "OPENAI_API_KEY=$OPENAI_API_KEY" > .env
        echo "PROXYCURL_API_KEY=$PROXYCURL_API_KEY" > .env
        echo "TAVILY_API_KEY=$TAVILY_API_KEY" > .env
      fi


vscode:
  extensions:
    - ms-python.python
    
