tasks:
  - name: Python Setup
    before: pip install --user pipenv
    init: |  
    unset PIP_USER
    pipenv install
    pipenv install python-dotenv
  command: |
    pipenv shell

vscode:
  extensions:
    - ms-python.python
    