tasks:
  - name: Python Setup
    before: pip install --user pipenv
    init: |  
      unset PIP_USER
      unset PROMPT_COMMAND
      pipenv install
      pipenv install python-dotenv
    command: |
      pipenv shell

  - name: Restore .env file
    command: |
      if [ -f .env ]; then
        echo "Found .env in workspace"
      else
        echo "Creating .env file"
        echo "VARIABLE_NAME=${VARIABLE_NAME}" > .env
      fi


vscode:
  extensions:
    - ms-python.python
    
